[package]
name = "ya-rand"
version = "0.1.0"
edition = "2021"
description = "A crate for simple and fast random number generation"
documentation = "https://docs.rs/ya-rand"
repository = "https://github.com/silverstillisntgold/ya-rand"
categories = ["algorithms", "no-std"]
keywords = ["chacha", "rand", "random", "rng", "xoshiro"]
license = "MIT"

# See crate-level documentation for explanantion of features.
[features]
default = ["std"]
inline = []
secure = ["dep:rand_chacha"]
std = ["getrandom/std", "rand_chacha?/std"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
getrandom = "0.3"
rand_chacha = { version = "0.9", default-features = false, optional = true }

[dev-dependencies]
fastrand = "2.3"
rand = "0.9"
rayon = "1.10"
