[package]
name = "ya-rand"
version = "2.0.2"
edition = "2024"
rust-version = "1.95"
description = "A crate for simple and fast random number generation"
documentation = "https://docs.rs/ya-rand"
repository = "https://github.com/silverstillisntgold/ya-rand"
license = "MIT"
keywords = ["chacha", "rand", "random", "rng", "xoshiro"]
categories = ["algorithms", "no-std"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
chachacha = { version = "0.5", features = ["_internal"], optional = true }
getrandom = "0.4"

[dev-dependencies]
chacha20 = { version = "0.10", default-features = false, features = ["rng"] }
fastrand = "2.5"
oorandom = "11.1"
rand = "0.10"
rayon = "1.12"

[features]
default = ["secure", "std"]
alloc = []
inline = []
secure = ["dep:chachacha"]
std = ["alloc", "getrandom/std"]
