[package]
name = "ya-rand"
version = "0.1.0"
edition = "2021"

# See crate-level documentation for explanantion of features.
[features]
default = ["std"]
inline = []
secure = ["dep:rand_chacha"]
std = ["getrandom/std", "rand_chacha?/std"]

[dependencies]
getrandom = "0.3"
rand_chacha = { version = "=0.9.0-beta.1", default-features = false, optional = true }

[dev-dependencies]
fastrand = "2.3"
rand = "0.8"
rayon = "1.10"
