[package]
name = "ya-rand"
version = "0.1.0"
edition = "2021"

# See crate-level documentation for explanantion of features.
[features]
default = ["std"]
inline = []
secure = ["dep:rand_chacha"]
std = ["getrandom/std", "rand_chacha?/std"]

[dependencies]
getrandom = "=0.3.0-rc.0"
rand_chacha = { version = "=0.9.0-beta.1", default-features = false, optional = true }
rayon = "1.10"
