name: ci
on: [pull_request, push]

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm]
        toolchain: [beta, nightly, stable]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -C target-cpu=native
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Update dependencies
        run: cargo update
      - name: Build tests
        run: cargo test --no-run
      - name: Run tests
        run: cargo test
