name: "run tests on stable"
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: echo "RUSTFLAGS=-Ctarget-cpu=native" >> "$GITHUB_ENV"
      - run: cargo update
      - run: cargo test --no-run
      - run: cargo test
